### ISSUE TITLE
SMAPI 3.0 Build Not Uploaded to Nexus

### ISSUE THREAD

**Issue by rikai** [mopquill/Mopsys-Ranch-Livin#2]
Getting the following errors when launching on the latest stable version of SMAPI and figured these [should be addressed with SMAPI 3.0 on the horizon](https://stardewvalleywiki.com/Modding:Migrate_to_SMAPI_3.0).

>[SMAPI] Mopsy's Ranch Livin' will break in the upcoming SMAPI 3.0 (legacy events are deprecated since SMAPI 2.9).

Looks like this may have been taken care of in #1, however, a new update was never pushed to Nexus so just consider this a friendly reminder issue that's tracking that process. :)

**Comment by mpql** [comment]
I've been super busy with work, I haven't had time to do this, and unfortunately, my Visual Studio is not launching for some reason, yaaaay. I'll try to get this done soon.

**Comment by mpql** [comment]
Updated the mod. Light testing shows it to be working without any bugs. It's uploaded both to [**Releases** here on GitHub](https://github.com/mopquill/Mopsys-Ranch-Livin/releases) and [the **Files** section on NexusMods](https://www.nexusmods.com/stardewvalley/mods/2200?tab=files). Thanks for the issue poking me.
